---
- name: Installing package
  hosts: all
  become: true
  gather_facts: no
  tasks:
  - name: Installing httpd package
    yum:
     name: httpd
     state: installed
  - name: Starting the services
    service:
     name: httpd 
     state: started
  - name: Copying index to html
    copy:
      src: /home/ansadmi/playbooks/index.html
      dest: /var/www/html
